### ISSUE TITLE
ConstrainEleCalculator NullPointerException

### ISSUE THREAD

**Issue by the-lenoz** [tordanik/OSM2World#220] opened 2024-07-18 13:34 UTC
Hello!

I used osm2world on many files with ConstrainEleCalculator and Linear interpolator, and got the following error when processing some of them:
`java.lang.NullPointerException: Cannot read field "y" because the return value of "org.osm2world.core.map_elevation.data.EleConnector.getPosXYZ()" is null
        at org.osm2world.core.map_elevation.creation.SimpleEleConstraintEnforcer.enforceConstraints(SimpleEleConstraintEnforcer.java:164)
        at org.osm2world.core.map_elevation.creation.ConstraintEleCalculator.calculateElevations(ConstraintEleCalculator.java:56)
        at org.osm2world.core.ConversionFacade.calculateElevations(ConversionFacade.java:441)
        at org.osm2world.core.ConversionFacade.createRepresentations(ConversionFacade.java:291)
        at org.osm2world.core.ConversionFacade.createRepresentations(ConversionFacade.java:240)
        at org.osm2world.viewer.model.Data.loadOSMData(Data.java:90)
        at org.osm2world.viewer.control.actions.AbstractLoadOSMAction$LoadOSMThread.run(AbstractLoadOSMAction.java:118)`
Then I tried to run osm2World through IDE with debugger and breakpoint on line with error. I got information that position of one node was set only for X and Z but not Y, so posXYZ = null. 
I also tried to add null-checker and skip these nodes without changing averageEle (I substracted number of skipped nodes from stiffSet size for division) but in this case I got all the terrain with 0 Y-coord and "flying" objects. With same config I processed 396 files success with correct elevation and landform. 
So, thanks for this well-working tool! Is this bug known or not? If necessary I can attach osm file

**Comment by tordanik** [comment] 2024-07-22 10:36
The elevation calculation code is quite experimental in general, but this particular bug isn't something I recognize. SimpleEleConstraintEnforcer assumes that all EleConnectors have an initial elevation value based on terrain elevation in that spot. This is done in `ConversionFacade.calculateElevations` and (at first glance) should only fail if the interpolator (LinearInterpolator in your case) throws an exception from its interpolateEle method. Does the console output contain any error messages related to `LinearInterpolator`?

If you want me to have a look at it myself, it would be useful to have the broken broken file available for debugging (and perhaps one working file as well). In addition to the OSM data, I would likely also need the elevation data you're using to reproduce the error.

**Comment by the-lenoz** [comment] 2024-07-29 19:32
Yes, I also found an error in InterpolateEle method:
`
ERROR: Cannot invoke "org.osm2world.core.map_elevation.creation.DelaunayTriangulation$DelaunayTriangle.getPoint(int)" because "currentTriangle" is null
Caused by: java.lang.NullPointerException: Cannot invoke "org.osm2world.core.map_elevation.creation.DelaunayTriangulation$DelaunayTriangle.getPoint(int)" because "currentTriangle" is null
	at org.osm2world.core.map_elevation.creation.DelaunayTriangulation.getEnlosingTriangle(DelaunayTriangulation.java:825)
	at org.osm2world.core.map_elevation.creation.LinearInterpolator.interpolateEle(LinearInterpolator.java:38)
	at org.osm2world.core.ConversionFacade.lambda$calculateElevations$9(ConversionFacade.java:434)
	at org.osm2world.core.util.FaultTolerantIterationUtil.forEach(FaultTolerantIterationUtil.java:24)
	at org.osm2world.core.util.FaultTolerantIterationUtil.forEach(FaultTolerantIterationUtil.java:36)
	at org.osm2world.core.ConversionFacade.calculateElevations(ConversionFacade.java:432)
	at org.osm2world.core.ConversionFacade.createRepresentations(ConversionFacade.java:291)
	at org.osm2world.core.ConversionFacade.createRepresentations(ConversionFacade.java:240)
	at org.osm2world.console.Output.output(Output.java:140)
	at org.osm2world.console.OSM2World.executeArgumentsGroup(OSM2World.java:218)
	at org.osm2world.console.OSM2World.main(OSM2World.java:151)
`
There are few errors like this. 
I use bboxes with OVERPASS api, so, this is a command to reproduce error:
`java -jar osm2world-0.4.0-SNAPSHOT.jar --input_mode OVERPASS --input_bbox 55.78951805910,37.90696730699 55.80747721680,37.93886392223 -o /tmp/test.obj --config config.properties`
I can't send file which is "broken" with this error because osm2world crashes and does not write any output file.

All errors persist for same data so there are no working file for the broken OSM data.

Here is my config, it's just modified standard.properties file:
[config.properties.txt](https://github.com/user-attachments/files/16418224/config.properties.txt)

**Comment by tordanik** [comment] 2024-08-13 10:09
Unfortunately, I can't reproduce the issue with the properties file and command line you provided to me. Can you tell which revision you built the osm2world-0.4.0-SNAPSHOT.jar from, and whether this issue might already be resolved in the latest version of the code in the repository?

**Comment by the-lenoz** [comment] 2024-08-15 16:03
I just tested and was convinced that bug appears even on the latest release from osm2world.org. 
Tested on the following file - [map.osm.txt](https://github.com/user-attachments/files/16627207/map.osm.txt)

With ConstrainEleCalculator and Linear interpolator

**Comment by tordanik** [comment] 2024-08-19 15:42
Thank you for this additional information. I've successfully reproduced the issue and will look into possible solutions.

**Comment by tordanik** [comment] 2024-08-22 12:22
a42ff54 addresses this issue by skipping connectors with null values in ConstraintEleCalculator's methods.

Thanks for your thorough bug report. If you still encounter issues, please don't hesitate to let me know.

**Closed by tordanik** 2024-08-22 12:22 UTC
